basePath: /api/
definitions:
  main.CalibrateInput:
    properties:
      j1:
        type: boolean
      j2:
        type: boolean
      j3:
        type: boolean
      j4:
        type: boolean
      j5:
        type: boolean
      j6:
        type: boolean
      speed:
        type: integer
      tr:
        type: boolean
    type: object
  main.JointDirections:
    properties:
      j1:
        type: boolean
      j2:
        type: boolean
      j3:
        type: boolean
      j4:
        type: boolean
      j5:
        type: boolean
      j6:
        type: boolean
      tr:
        type: boolean
    type: object
  main.MoveStepperInput:
    properties:
      accdur:
        type: integer
      accspd:
        type: integer
      dccdur:
        type: integer
      dccspd:
        type: integer
      j1:
        type: integer
      j2:
        type: integer
      j3:
        type: integer
      j4:
        type: integer
      j5:
        type: integer
      j6:
        type: integer
      speed:
        type: integer
      tr:
        type: integer
    type: object
info:
  contact: {}
  description: The arm API for ArmOS to interact with a variety of different robotic
    arms, starting with the AR3. It uses the basic interface of `x,y,z,a,b,c` for
    control.
  title: ArmOS arm API
  version: "0.1"
paths:
  /calibrate:
    post:
      consumes:
      - application/json
      description: Calibrates the robot. Should be done occasionally to affirm the
        robot is where we think it should be.
      parameters:
      - description: joints to calibrate
        in: body
        name: joints
        required: true
        schema:
          $ref: '#/definitions/main.CalibrateInput'
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Calibrate the arm
      tags:
      - low_level
  /directions:
    get:
      description: Returns current direction of arm's motors.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.JointDirections'
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Returns direction of arm joints
      tags:
      - setup
  /move:
    post:
      consumes:
      - application/json
      description: Moves the robot's stepper motors.
      parameters:
      - description: steppers coordinates
        in: body
        name: move
        required: true
        schema:
          $ref: '#/definitions/main.MoveStepperInput'
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Move the arm's stepper motors
      tags:
      - low_level
  /ping:
    get:
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: A pingable endpoint
      tags:
      - dev
  /set_directions:
    post:
      consumes:
      - application/json
      description: Sets up the robots joints. This only has to be done once during
        the setup of the robot.
      parameters:
      - description: direction of joints
        in: body
        name: directions
        required: true
        schema:
          $ref: '#/definitions/main.JointDirections'
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Sets direction of arm joints
      tags:
      - setup
swagger: "2.0"
